dado = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(dado)))
print('Só tem espaços?', dado.isspace())
print('É um número?', dado.isnumeric())
print('É alfabético?', dado.isalpha())
print('É alfanumérico?', dado.isalnum())
print('Está maiúscula?', dado.isupper())
print('Está minúscula?', dado.islower())
print('Está capitalizada?', dado.istitle())